gitGraph
    commit id: "1"
    branch atm-simulation-feature
    checkout atm-simulation-feature
    commit id: "2"
    commit id: "3"
    branch atm-simulation-feature-xxxx
    branch atm-simulation-feature-yyyy
    branch atm-simulation-feature-zzzz
    checkout atm-simulation-feature-xxxx
    commit id: "4"
    commit id: "5"
    checkout atm-simulation-feature-yyyy
    commit id: "6"
    commit id: "7"
    checkout atm-simulation-feature-zzzz
    commit id: "8"
    checkout atm-simulation-feature
    merge atm-simulation-feature-xxxx id:"MERGE1"
    merge atm-simulation-feature-yyyy id:"MERGE2"
    merge atm-simulation-feature-zzzz id:"MERGE3"
    checkout main
    merge atm-simulation-feature id:"MERGE4"
